### PR TITLE
curve/pfs: devel image

### PR DESCRIPTION
**Pull request by Cyber-SiKu**
Signed-off-by: Cyber-SiKu <Cyber-SiKu@outlook.com>

### CODE REVIEW

**Comment by mrdrivingduck** [comment]
@Cyber-SiKu LGTM. One question: it seems that your Dockerfile has hard-coded some platform specific instructions, like x86_64. Does Curve SDK support building on aarch64 platform?

**Comment by mrdrivingduck** [comment]
Also, it seems that this Dockerfile will still clone PFS from official repository, instead of PFS for Curve. Would you check that? @Cyber-SiKu

**Comment by Cyber-SiKu** [comment]
> Also, it seems that this Dockerfile will still clone PFS from official repository, instead of PFS for Curve. Would you check that? @Cyber-SiKu

fix

**Comment by mrdrivingduck** [comment]
@Cyber-SiKu Let's leave the ARM64 compilation issue to the future.

**Pull request merged**
